
spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  cloud:
    config:
      label: 1.0.0
      name: @pom.artifactId@
      profile: ${spring.profiles.active}
      username: admin
      password: admin
      fail-fast: true
      uri: http://localhost:8766
    bus:
      trace:
        enabled: true
    stream:
      default-binder: rabbit
