spring:
  profiles: dev
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka-server1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/